# Generated by Django 4.2.3 on 2023-07-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upgrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='show',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='show',
            name='date',
            field=models.DateField(verbose_name='Show Date'),
        ),
    ]
