# Generated by Django 4.2.3 on 2023-07-28 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_upgrades_alter_show_options_alter_show_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upgrades',
            new_name='Upgrade',
        ),
    ]
