# Generated by Django 4.2.3 on 2023-07-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_upgrades_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='upgrades',
            field=models.ManyToManyField(to='main_app.upgrade'),
        ),
    ]
